### ISSUE TITLE
CR char are transformed into spaces

### ISSUE THREAD

**Issue by amoissant** [bahmutov/as-a#11]
I created a .ini file under windows and by default my editor add CRLF at the end of each line.

It introduce white spaces in my env var as displayed into Cypress : 
![Capture](https://user-images.githubusercontent.com/7916968/128055550-5ec3709d-bf4b-4058-8a89-05ad474867b2.PNG)

I then converted my file with CRLF to only LF and it works in cypress.

Here is an example of file (to rename as .as-a.ini, github don't support .ini files)
[as-a.txt](https://github.com/bahmutov/as-a/files/6925849/as-a.txt)

Is it possible to make you tool compatible with windows end line chars ?

Anthony

**Comment by bahmutov** [comment]
Hmm, it is weird, I would be open to a pull request fixing this

**Comment by kalyansatvik2727** [comment]
Getting the below error while running >as-a npx cypress open and >npx as-a test cypress open in windows.
![as-a_issue](https://user-images.githubusercontent.com/55090515/140633851-16e8ec86-1c7a-4c55-a620-0541698f5a3d.png)

I created .ini file as per the doc.

**Comment by kalyansatvik2727** [comment]
I have tried configuring .ini file as below too
[test]
CYPRESS_username=Admin
CYPRESS_password=admin123

**Comment by przedab** [comment]
I have the same situation - v.2.2.2
![image](https://user-images.githubusercontent.com/128488979/228465159-0e8d45e1-eb8f-417b-9c86-bff2aff24c51.png)
![image](https://user-images.githubusercontent.com/128488979/228465371-d397a1cd-3bfb-4215-90d4-4992823bd8fb.png)
