### ISSUE TITLE
The 'got' package before 11.8.5 and 12.1.0 for Node.js allows a redirect to a UNIX socket.

### ISSUE THREAD

**Issue by iwt-ttaskov** [bahmutov/as-a#15]
Hi @bahmutov ,
'as-a' uses the package 'got' v3.3.1. This is a very old version of 'got' (more than 7 years old) and now it turns out to be vulnerable by allowing a redirect to a UNIX socket (see https://github.com/advisories/GHSA-pfrx-2q88-qq97).
By executing `yarn npm audit --recursive` I get this:

`└─ got: 3.3.1
├─ Issue: Got allows a redirect to a UNIX socket
├─ URL: https://github.com/advisories/GHSA-pfrx-2q88-qq97
├─ Severity: moderate
├─ Vulnerable Versions: <11.8.5
├─ Patched Versions: >=11.8.5
├─ Via: as-a
└─ Recommendation: Upgrade to version 11.8.5 or later
`

Could you please upgrade the 'got' version to 11.8.5 or later to resolve this vulnerability issue?

Thank you in advance

**Comment by bahmutov** [comment]
```
$ npm ls got
as-a@0.0.0-development /Users/glebbahmutov/git/as-a
└─┬ simple-bin-help@1.6.0
  └─┬ update-notifier@0.5.0
    └─┬ latest-version@1.0.1
      └─┬ package-json@1.2.0
        └── got@3.3.1
```
