### ISSUE TITLE
Recommended way to handle secrets?

### ISSUE THREAD

**Issue by ghost** [bahmutov/as-a#9]
Hello,

I would like to know what is the recommended way to handle secrets in an .as-a.ini file.

Let's say that, besides some urls and ports used in various profiles (dev, prod, etc.), I would also need to have a secret value. For example:
```
[E2E]
CLIENT_PORT=8001
SERVER_PORT=3001
CYPRESS_API_URL=http://localhost:3001/api
BROWSER=none
SOME_API_KEY=some-secret-value

[DEV]
CLIENT_PORT=3000
SERVER_PORT=4000
REACT_APP_API_URL=http://localhost:4000/api
SOME_API_KEY=some-secret-value

[PROD]
CLIENT_PORT=8080
SERVER_PORT=4000
REACT_APP_API_URL=https://til.now.sh/api
SOME_API_KEY=some-secret-value
```

Obviously, I don't want to make publicly available this data.

Is it ok to add a placeholder for the secret value? Something like: ```SOME_API_KEY=[put-the-secret-value-here]```. And let anyone who clones my project to put the real value into that placeholder.

Does this sound right? Is there a better way? Maybe put only all non-secret values in the .as-a.ini file and set all the secret values through environment variables before executing any script.

Thanks

**Comment by bahmutov** [comment]
I would argue the opposite is better
- put all public environment variables that do not need to be secret into `.env` file.
- specify additional secrets to be placed into `~/.as-a/.as-a.ini`, maybe by listing them in the README section
